global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using CompanyEmployees.Extensions;
global using System.IO;
global using Microsoft.AspNetCore.HttpOverrides;
global using NLog;
global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using EmployeeManagementSystem.Contracts;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Http;
global using EmployeeManagementSystem.Presentation;
global using EmployeeManagementSystem.Repository.Extensions;
global using EmployeeManagementSystem.Service.Contracts;
global using EmployeeManagementSystem.Shared.DTOs;
global using Microsoft.AspNetCore.Mvc;

